### PR TITLE
[AWIBOF-7472] Fix for OpenTelemetry build issue

### PR DESCRIPTION
**Pull request by joshyunho**
Add libssl-dev to pkgdep.sh

Signed-off-by: yunho.yang <yunho.yang@samsung.com>

### CODE REVIEW

**Review by junghyun-34 — APPROVED** [review]

**Review by junghyun-34 — APPROVED** [review]
LGTM

**Review by minjoon-ahn — DISMISSED** [review]
감사합니다

**Review by junghyun-34 — APPROVED** [review]
Great work!

**Review by hsung-yang — APPROVED** [review]
LGTM

**Pull request merged**
