### PR TITLE
Telemetry commands changed to use Kouros

### PR DESCRIPTION
**Pull request by aswinssir**
GETTELEMETRYPROPERTY, SETTELEMETRYPROPERTY, START_TELEMETRY commands changed

### CODE REVIEW

**Review by mjlee34 — DISMISSED** [review]

**Review by syeonshin — APPROVED** [review]
수고하셨습니다.

**Review by mjlee34 — APPROVED** [review]

**Comment by jg121-lim** [comment]
고생많으셨습니다.

**Review by jg121-lim — APPROVED** [review]
고생많으셨습니다

**Comment by mjlee34** [comment]
Will not merge this pull request for unknown error. Will merge the code via another pull request.

**Pull request closed without merging**
