### PR TITLE
[AWIBOF-7143] Change mio and mpio pool capacity

### PR DESCRIPTION
**Pull request by MunseopLim**
- reduced the sizes to smaller

Signed-off-by: munseop.lim <munseop.lim@samsung.com>

### CODE REVIEW

**Comment by MunseopLim** [comment]
pool size를 줄였습니다

**Review by dhihm — APPROVED** [review]
감사합니다. 던던스!

**Review by ray5273 — APPROVED** [review]
수고하셨습니당

**Review by yyu-nim — APPROVED** [review]
수고하셨습니다!!!

**Pull request merged**
