### PR TITLE
[AWIBOF-7259] Add make install step to README.md

### PR DESCRIPTION
**Pull request by mjlee34**
Add make install step as optional to README.md.

Signed-off-by: mjlee34 <jun20.lee@samsung.com>

### CODE REVIEW

**Review by minjoon-ahn — APPROVED** [review]
lg2m

**Review by aswinssir — APPROVED** [review]
LGTM

**Review by hsung-yang — APPROVED** [review]
LGTM

**Review by hsung-yang — APPROVED** [review]

**Review by minjoon-ahn — APPROVED** [review]

**Review by ringopow — APPROVED** [review]
수고하셨습니다~

**Pull request merged**
