### PR TITLE
[AWIBOF-6853] Add a global flag to CLI client for command timeout

### PR DESCRIPTION
**Pull request by mjlee34**
Add a global flag to CLI client that specifies a timeout for the command.

Update docs accordingly.

### CODE REVIEW

**Review by minjoon-ahn — APPROVED** [review]
lg2m

**Comment by mjlee34** [comment]
전 Commit이 섞여있습니다. flags.go 와 root.go가 변경점입니다.

**Review by mmschoi — DISMISSED** [review]

**Comment by mmschoi** [comment]
고생하셨습니다!!

**Review by hsung-yang — APPROVED** [review]
LGTM

**Review by junghyun-34 — APPROVED** [review]
lgtm

**Pull request merged**
